import type { Metadata } from 'next';
import './globals.css';
import Layout from '@/components/layout/Layout';
import { BottomNavigation } from '@/components/layout/BottomNavigation';

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// });

export const metadata: Metadata = {
  title: 'Glowberry',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        cz-shortcut-listen="true"
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Layout>{children}</Layout>
        <BottomNavigation />
      </body>
    </html>
  );
}
